version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: budgetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ejnimona@4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  backend:
    build: ./budget-app-backend
    environment:
      DATABASE_URL: postgres://postgres:Ejnimona@4@postgres/budgetdb
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  frontend:
    build: ./budget-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres-data:
